name: actionlint

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.ya?ml'
      - 'Formula/a/actionlint.rb'
      - 'Formula/s/shellcheck.rb'
      - 'Formula/z/zizmor.rb'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  OSPACK_DEVELOPER: 1
  OSPACK_NO_AUTO_UPDATE: 1
  OSPACK_NO_ENV_HINTS: 1

permissions: {}

jobs:
  workflow_syntax:
    if: github.repository_owner == 'Ospack'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ospack/ubuntu22.04:master
    steps:
      - name: Set up Ospack
        id: setup-ospack
        uses: Ospack/actions/setup-ospack@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Install tools
        run: ospack install actionlint shellcheck zizmor

      - name: Set up GITHUB_WORKSPACE
        env:
          OSPACK_TAP_REPOSITORY: ${{ steps.setup-ospack.outputs.repository-path }}
        run: |
          # Annotations work only relative to GITHUB_WORKSPACE
          (shopt -s dotglob; rm -rf "${GITHUB_WORKSPACE:?}"/*; mv "${OSPACK_TAP_REPOSITORY:?}"/* "$GITHUB_WORKSPACE")
          rmdir "$OSPACK_TAP_REPOSITORY"
          ln -vs "$GITHUB_WORKSPACE" "$OSPACK_TAP_REPOSITORY"

      - run: zizmor --format sarif . > results.sarif

      - name: Upload SARIF file
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: results.sarif
          path: results.sarif

      - name: Set up actionlint
        run: |
          # Setting `shell: /bin/bash` prevents shellcheck from running on
          # those steps, so let's change them to `shell: bash` for linting.
          sed -i 's|shell: /bin/bash -x|shell: bash -x|' .github/workflows/*.y*ml
          # The JSON matcher needs to be accessible to the container host.
          cp "$(ospack --repository)/.github/actionlint-matcher.json" "$HOME"
          echo "::add-matcher::$HOME/actionlint-matcher.json"

      - run: actionlint

  upload_sarif:
    needs: workflow_syntax
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Download SARIF file
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: results.sarif
          path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1
        with:
          sarif_file: results.sarif
          category: zizmor
