name: Bump formulae on schedule or request

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours from 1 through 23 with an offset of 45 minutes
    - cron: "45 1-23/3 * * *"

permissions:
  contents: read

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    if: github.repository_owner == 'Ospack'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ospack/ubuntu22.04:master
    env:
      GNUPGHOME: /tmp/gnupghome
    steps:
      - name: Set up Ospack
        id: set-up-ospack
        uses: Ospack/actions/setup-ospack@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Configure Git user
        uses: Ospack/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'fortishield' }}

      - name: Set up commit signing
        uses: Ospack/actions/setup-commit-signing@master
        with:
          signing_key: ${{ secrets.fortishield_GPG_SIGNING_SUBKEY }}

      - name: Bump formulae
        env:
          OSPACK_TEST_BOT_AUTOBUMP: 1
          OSPACK_GITHUB_API_TOKEN: ${{ secrets.OSPACK_CORE_REPO_WORKFLOW_TOKEN }}
          OSPACK_GIT_COMMITTER_NAME: fortishield
          OSPACK_GIT_COMMITTER_EMAIL: 1589480+fortishield@users.noreply.github.com
          OSPACK_GPG_PASSPHRASE: ${{ secrets.fortishield_GPG_SIGNING_SUBKEY_PASSPHRASE }}
          FORMULAE: ${{ inputs.formulae }}
        run: |
          OSPACK_BUMP=(ospack bump --no-fork --open-pr --formulae)
          if [[ -n "${FORMULAE-}" ]]; then
            xargs "${OSPACK_BUMP[@]}" <<<"${FORMULAE}"
          else
            "${OSPACK_BUMP[@]}" --auto --tap=Ospack/core
          fi
