name: Populate gem cache

on:
  pull_request:
    paths:
      - .github/workflows/cache.yml
  push:
    paths:
      - .github/workflows/cache.yml
    branches:
      - master
  schedule:
    - cron: '30 19/6 * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  OSPACK_DEVELOPER: 1
  OSPACK_NO_AUTO_UPDATE: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: cache-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  determine-runners:
    if: github.repository_owner == 'Ospack'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ospack/ubuntu22.04:master
    outputs:
      runners: ${{ steps.determine-runners.outputs.runners }}
    steps:
      - name: Set up Ospack
        id: set-up-ospack
        uses: Ospack/actions/setup-ospack@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Determine runners to use for this job
        id: determine-runners
        env:
          OSPACK_MACOS_TIMEOUT: 30
        run: ospack determine-test-runners --all-supported

  cache:
    needs: determine-runners
    strategy:
      matrix:
        include: ${{ fromJson(needs.determine-runners.outputs.runners) }}
      fail-fast: false
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: ${{ matrix.timeout }}
    steps:
      - name: Set up Ospack
        id: set-up-ospack
        uses: Ospack/actions/setup-ospack@master
        with:
          core: false
          cask: false
          test-bot: true

      - name: Cleanup runner
        if: matrix.cleanup
        working-directory: ${{ runner.temp }}
        run: ospack test-bot --only-cleanup-before

      - name: Get cache key
        id: cache-key
        run: |
          cache_key_prefix="${RUNNER_OS}"
          if [ "${RUNNER_OS}" = macOS ]
          then
            macos_version="$(sw_vers -productVersion)"
            cache_key_prefix="${macos_version%%.*}-$(uname -m)"
          fi
          echo "prefix=${cache_key_prefix}" >> "${GITHUB_OUTPUT}"

      - name: Cache Ospack Bundler gems
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ steps.set-up-ospack.outputs.gems-path }}
          key: ${{ steps.cache-key.outputs.prefix }}-rubygems-${{ steps.set-up-ospack.outputs.gems-hash }}
          restore-keys: ${{ steps.cache-key.outputs.prefix }}-rubygems-

      - name: Setup Ospack test environment
        working-directory: ${{ runner.temp }}
        run: ospack test-bot --only-setup
